* DONE exo 1
  Un télécopieur groupe 3 a une résolution de 300 dpi (dot per inch). On
  utilise le réseau téléphonique à 9600
  bits/s pour transférer une image A4 supposée pleine. Rappel : 1 inch = 2,54
  cm, A4 = 21cm x 29,7cm

** exo 1.1
   Déterminer le temps de transmission, en déduire le taux de compression
   nécessaire pour que cette page
   soit transmise en 1 minute maximum. Un point sera supposé être représenté
   sur un bit (point blanc bit à
   0, point noir bit à 1).

   (300*8.27*300*11.69) = 8700867
   8700867/9600 = 906.340312
   906.340312/60 = 15.105672

** exo 1.2
   Le télécopieur groupe 4 (canal B RNIS) a une résolution de 400 dpi,
   utilise une ligne à 64kbps et transfère
   une page en 3s, quel est le taux de compression ?

#+BEGIN_SRC
   400*8.27*400*11.69 = 1.546821e7
   1.546821e7/64000 = 241.690781
         241.690781/3 = 80.563594
#+END_SRC


* DONE exo 2
  Si une fibre optique a un débit D = 155 Mb/s et une longueur L = 3000 km,
  combien de temps faut-il pour
  recevoir à l’autre bout la fin d’un paquet de 512 octets ? Application
  numérique : V = 2.108 m/s.
  À présent, on utilise une paire torsadée de débit D = 2 Mb/s, comparer les
  résultats en utilisant la même
  vitesse de propagation.
** exo 2.1
#+BEGIN_SRC
   (512*8)/(155*1000000)+(3000000/2.10e8) = 0.014312

#+END_SRC
** exo 2.2

#+BEGIN_SRC
   (512*8)/(2*1000000)+(3000000/2.10e8) = 0.016334

#+END_SRC
* DONE exo 3
  On suppose qu’une ligne de transmission a un taux d’erreur bit (BER) de
  10−4
  en moyenne. Un protocole
  de niveau 2 utilise des trames de 256 octets.
  – Quel est le pourcentage de trames erronées si l’on envoie 100 trames ?
  – Quel est le débit effectif si ces 100 trames sont envoyées en 2 s ?
  – En conservant la même quantité de données, quel est le débit si les
  trames ont une taille de 53 octets ?
** exo 3.1
#+BEGIN_SRC
   (256*8) = 2048
   pow(1-pow(10,-4),2048) = 0.814802
   1-0.814802 = 0.185198   

#+END_SRC
** in 2 seconds
#+BEGIN_SRC
   (2048*(100*0.814802))/2 = 83435.7248
#+END_SRC
** trame of 53Bytes

#+BEGIN_SRC
   204800/(53*8) = 483.018868
   ((53*8)*(483*pow(1-pow(10,-4),424)))/2 = 98144.956052
#+END_SRC
* DONE exo 4
  Une série de trames de 1000 bits doit être transmise en utilisant un
  protocole Idle RQ. Déterminer le taux
  d’utilisation du lien pour les supports suivants, en supposant des débits
  de transmission de 1 kb/s et 1 Mb/s. On
  considèrera des acquittements de 10 octets. La vitesse de propagation est
  de 2.108 m/s et le taux d’erreurs est
  négligeable :
  – une paire torsadée de 1 km de long
  – une ligne louée de 200 km de long
  – un lien satellite de 50000 km
  Rappel : Idle RQ (Idle Repeat Request) - quand on envoie une trame, on
  amorce un timer. L’émetteur attend
  un ACK. Si le timer expire, la trame est retransmise (implicitement).
  Lorsqu’un acquittement est reçu la
  trame suivante est envoyée.

** 1km
#+BEGIN_SRC
   size = 10*8 = 80 
#+END_SRC
*** 1kbs
#+BEGIN_SRC
    (80/1000)+(1000/2.10e8) = 0.080005
    (1000/1000)+(1000/2.10e8) = 1.000005 
    (80/1000)+(1000/2.10e8)+ (1000/1000)+(1000/2.10e8) = 1.08001  
    debit utile
    = d-utile/debit
    1000/1.08001/1000 = 0.925917
#+END_SRC
*** 1mb/s
#+BEGIN_SRC
    (80/1000000)+(1000/2.10e8) = 8.47619e-5 
    (1000/1000000)+(1000/2.10e8) = 0.001005  
    (80/1000000)+(1000/2.10e8)+ (1000/1000000)+(1000/2.10e8) = 0.00109   
    debit utile
    1000/0.00109/1000000 = 0.917431
#+END_SRC
** 200km
*** 1kbs
#+BEGIN_SRC
    (80/1000)+(200000/2.10e8) = 0.080952
    (1000/1000)+(200000/2.10e8) = 1.000952  
    (80/1000)+(200000/2.10e8) + (1000/1000)+(200000/2.10e8) = 1.081905   
    1000/1.081905/1000 = 0.924296
#+END_SRC
*** 1mbs
#+BEGIN_SRC
    (80/1000000)+(200000/2.10e8) = 0.001032
    (1000/1000000)+(200000/2.10e8) = 0.001952 
    (80/1000000)+(200000/2.10e8) + (1000/1000000)+(200000/2.10e8) = 0.002985  
    1000/0.002985/1000000 = 0.335008
#+END_SRC
** 50000km
*** 1kbs
#+BEGIN_SRC
    (80/1000)+(50000000/2.10e8) = 0.318095
    (1000/1000)+(50000000/2.10e8) = 1.238095 
    (80/1000)+(50000000/2.10e8) + (1000/1000)+(50000000/2.10e8) = 1.55619  
    1000/((80/1000)+(50000000/2.10e8) + (1000/1000)+(50000000/2.10e8))/1000 = 0.642595
#+END_SRC
*** 1mbs
#+BEGIN_SRC
    (80/1000000)+(50000000/2.10e8) = 0.238175
    (1000/1000000)+(50000000/2.10e8) = 0.239095 
    (80/1000000)+(50000000/2.10e8) + (1000/1000000)+(50000000/2.10e8) = 0.47727  
    1000/((80/1000000)+(50000000/2.10e8) + (1000/1000000)+(50000000/2.10e8))/1000000 = 0.002095
#+END_SRC




* DONE exo 5

  Theorème de Nyquist : Soit g un signal auquel on applique en entrée un filtre
  passe-bas de bande passante H. 
  Le signal g peut-être entièrement reconstitué à partir d’un
  échantillonnage à 2H par seconde.

  Théorème de Nyquist (bis) : Si g comporte V niveaux significatifs, le débit
  maximal est : Dmax =  2H log2 V .
  V = numbber of possible values bits codeded  on the signal;
  V = 2^n
  Dmax = 2H .n
** 1.
   Les CD audio sont échantillonnés à 44,1 KHz. Selon vous pourquoi ?
   - 21 khz by each side on stereo 

** 2. 
   Un canal téléphonique a une bande passante de 3100Hz (entre 300Hz et
   3400Hz). Quel est le débit binaire

   (2 * 3100) = 6200
   théorique maximum ? Comment la plupart des modems peuvent avoir un
   débit supérieur.
   Dmax = (2*3100)*log2(V).
   by having a V being biger then 2;

* TODO exo 6

  Théorème de Shannon : Soit un canal de transmission de bande passante H.
  Soient S l’énergie du signal
  et N l’énergie du bruit. La capacité maximale de transmission, en bit/s est
  de :
#+begin_src
  C = H log2  (1 + S/N)
#+end_src

** 1.
   Une ligne téléphonique a une bande passante de 3100Hz et un rapport

#+BEGIN_SRC
   signal/bruit de 30 dB ( S/N =  xdB <=> x = 10 log10 S/N).
#+END_SRC
   Quel est le débit maximal théorique ?

#+BEGIN_SRC
   30db = 10*log10(x)
   3=log10(x);
   x = pow(10,3) = 1000
   x = 1000;
   H = 3100mhz
   C = 3100*log2(1001)
   C = 3100*10 = 31000
   aproximation 31kbits;
#+END_SRC
** 2.
   
   Pourquoi les connexions ADSL (Asymetric Digital Subscriber Line)
   utilisant pourtant les lignes téléphoniques
   atteignent des débits de plusieurs Méga ?
   
   because we dont use the telefone line but a numerique line and the
   telefone works as VOIP (voice over IP);
#+BEGIN_SRC
#+END_SRC

** 3.

   Quel dispositif permet d’utiliser simultanément son accès internet
   et son téléphone fixe ?
      
** 4.

   Pourquoi le débit n’est pas le même suivant la position
   géographique de l’abonné ?
   the debit goes down after 5 kilometres
* exo 8
  10GO 
  (10000000000*8)/2000000 = 40000 
  (40000/60)/60 = 11.111111
  
