
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 23 17:24:12 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompSymbol {
  /* terminals */
  public static final int ENDBLOCK = 35;
  public static final int MULT = 13;
  public static final int CHAR = 6;
  public static final int STR = 8;
  public static final int EQUALS = 27;
  public static final int SEMIC = 33;
  public static final int INT = 5;
  public static final int NOT = 17;
  public static final int AND = 18;
  public static final int RPAR = 32;
  public static final int INF = 22;
  public static final int OR = 25;
  public static final int COMMA = 36;
  public static final int BOOL = 9;
  public static final int CLASS = 12;
  public static final int DIV = 16;
  public static final int EXIT = 40;
  public static final int PLUS = 23;
  public static final int IF = 37;
  public static final int MIN = 15;
  public static final int MAIN = 4;
  public static final int ID = 43;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int NEWBLOCK = 34;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int NULL = 21;
  public static final int MOD = 14;
  public static final int EQ = 26;
  public static final int ELSE = 38;
  public static final int WHILE = 39;
  public static final int LIST = 10;
  public static final int FLOAT = 7;
  public static final int SUP = 24;
  public static final int NB = 44;
  public static final int STRING = 42;
  public static final int LPAR = 31;
  public static final int PROC = 2;
  public static final int DIFF = 30;
  public static final int POINTER = 11;
  public static final int FALSE = 20;
  public static final int GEQL = 28;
  public static final int STRUCT = 3;
  public static final int LEQL = 29;
}

