
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 16 11:43:46 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompSymbol {
  /* terminals */
  public static final int ID = 7;
  public static final int MULT = 6;
  public static final int error = 1;
  public static final int PLUS = 5;
  public static final int LPAR = 2;
  public static final int SEMIC = 4;
  public static final int RPAR = 3;
  public static final int EOF = 0;
}

