/* The following code was generated by JFlex 1.4.2 on 9/25/15 10:45 AM */


import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 9/25/15 10:45 AM from the specification file
 * <tt>/home/willian/Documents/M1-Class/compilation/m1compilationjwv/trunk/compilationProject/lexer/lexer.jflex</tt>
 */
class CompLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\1\0\1\5\1\3\22\0\1\54\1\14\1\11"+
    "\2\0\1\50\1\57\1\0\1\45\1\46\1\7\1\47\1\52\1\51"+
    "\1\0\1\6\1\10\11\2\1\61\1\53\1\15\1\13\1\16\2\0"+
    "\32\1\1\0\1\12\1\0\1\41\1\1\1\0\1\27\1\37\1\22"+
    "\1\24\1\23\1\35\1\33\1\34\1\30\2\1\1\36\1\26\1\31"+
    "\1\21\1\17\1\1\1\20\1\40\1\32\1\25\1\1\1\43\1\44"+
    "\1\42\1\1\1\55\1\60\1\56\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\1\5\1\3"+
    "\1\6\1\7\1\10\1\11\1\12\13\2\1\13\1\2"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\1"+
    "\1\23\1\24\1\25\1\26\3\27\1\30\1\27\2\0"+
    "\1\31\1\32\1\33\1\34\7\2\1\35\11\2\2\0"+
    "\20\2\1\0\4\2\1\36\1\37\1\2\1\40\1\41"+
    "\1\42\7\2\1\0\3\2\1\43\1\2\1\44\1\45"+
    "\4\2\1\46\1\0\1\2\1\47\2\2\1\50\2\2"+
    "\1\51\1\0\2\2\1\52\1\53\1\2\1\0\3\2"+
    "\1\0\1\54\1\55\1\56\12\0\1\57\16\0\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\144"+
    "\0\144\0\144\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\u041a\0\144\0\u044c\0\144\0\144\0\144\0\144\0\144"+
    "\0\144\0\144\0\u047e\0\144\0\144\0\144\0\144\0\144"+
    "\0\372\0\u012c\0\144\0\u04b0\0\u04e2\0\u0514\0\144\0\144"+
    "\0\144\0\144\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640"+
    "\0\u0672\0\226\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e"+
    "\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e"+
    "\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe"+
    "\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e"+
    "\0\u0c80\0\u0cb2\0\226\0\226\0\u0ce4\0\226\0\226\0\226"+
    "\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74"+
    "\0\u0ea6\0\u0ed8\0\u0f0a\0\226\0\u0f3c\0\226\0\226\0\u0f6e"+
    "\0\u0fa0\0\u0fd2\0\u1004\0\226\0\u1036\0\u1068\0\226\0\u109a"+
    "\0\u10cc\0\226\0\u10fe\0\u1130\0\226\0\u1162\0\u1194\0\u11c6"+
    "\0\226\0\226\0\u11f8\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2"+
    "\0\u1324\0\226\0\226\0\u1356\0\u1388\0\u13ba\0\u13ec\0\u141e"+
    "\0\u1450\0\u1482\0\u14b4\0\u14e6\0\u1518\0\144\0\u154a\0\u157c"+
    "\0\u15ae\0\u15e0\0\u1612\0\u1644\0\u1676\0\u16a8\0\u16da\0\u170c"+
    "\0\u173e\0\u1770\0\u17a2\0\u17d4\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\3\1\7\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\4\1\21\1\22\4\4\1\23\1\24\1\25\2\4"+
    "\1\26\1\27\1\30\1\31\1\32\1\4\1\33\1\4"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\3\1\44\1\45\1\46\1\47\3\50\1\51\1\3"+
    "\1\50\1\52\2\50\1\53\1\54\47\50\63\0\2\4"+
    "\5\0\1\4\6\0\22\4\1\0\3\4\17\0\1\5"+
    "\5\0\1\5\55\0\1\3\63\0\1\55\1\56\65\0"+
    "\1\57\61\0\1\60\61\0\1\61\61\0\1\62\47\0"+
    "\2\4\5\0\1\4\6\0\1\4\1\63\20\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\4\4\1\64"+
    "\15\4\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\15\4\1\65\1\4\1\66\2\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\17\4\1\67\2\4\1\0"+
    "\2\4\1\70\16\0\2\4\5\0\1\4\6\0\12\4"+
    "\1\71\3\4\1\72\3\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\6\4\1\73\13\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\1\4\1\74\20\4"+
    "\1\0\1\75\2\4\16\0\2\4\5\0\1\4\6\0"+
    "\10\4\1\76\6\4\1\77\2\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\11\4\1\100\10\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\2\4\1\101"+
    "\17\4\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\13\4\1\102\6\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\15\4\1\103\4\4\1\0\3\4\71\0"+
    "\1\104\16\0\1\50\50\0\3\55\1\6\1\3\55\55"+
    "\7\56\1\105\52\56\1\0\2\4\5\0\1\4\6\0"+
    "\2\4\1\106\17\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\13\4\1\107\6\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\10\4\1\110\11\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\10\4\1\111"+
    "\11\4\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\21\4\1\112\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\11\4\1\113\10\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\13\4\1\114\6\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\17\4\1\115\2\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\6\4"+
    "\1\116\13\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\1\117\21\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\17\4\1\120\2\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\2\4\1\121\17\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\21\4\1\122"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\2\4"+
    "\1\123\17\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\1\4\1\124\20\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\11\4\1\125\10\4\1\0\3\4"+
    "\71\0\1\126\5\0\6\56\1\3\1\105\52\56\1\0"+
    "\2\4\5\0\1\4\6\0\3\4\1\127\16\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\6\4\1\130"+
    "\13\4\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\1\4\1\131\20\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\21\4\1\132\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\4\4\1\133\15\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\13\4\1\134\6\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\4\4"+
    "\1\135\15\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\17\4\1\136\2\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\4\4\1\137\15\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\4\4\1\140\15\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\21\4"+
    "\1\141\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\10\4\1\142\11\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\13\4\1\143\6\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\17\4\1\144\2\4\1\0"+
    "\3\4\16\0\2\4\5\0\1\4\6\0\6\4\1\145"+
    "\2\4\1\146\10\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\17\4\1\147\2\4\1\0\3\4\71\0"+
    "\1\150\6\0\2\4\5\0\1\4\6\0\4\4\1\151"+
    "\15\4\1\0\3\4\16\0\2\4\5\0\1\4\6\0"+
    "\1\4\1\152\20\4\1\0\3\4\16\0\2\4\5\0"+
    "\1\4\6\0\10\4\1\153\11\4\1\0\3\4\16\0"+
    "\2\4\5\0\1\4\6\0\21\4\1\154\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\14\4\1\155\5\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\4\4"+
    "\1\156\15\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\13\4\1\157\6\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\2\4\1\160\17\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\4\4\1\161\15\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\3\4"+
    "\1\162\16\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\12\4\1\163\7\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\4\4\1\164\15\4\1\0\3\4"+
    "\71\0\1\165\6\0\2\4\5\0\1\4\6\0\5\4"+
    "\1\166\14\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\12\4\1\167\7\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\3\4\1\170\16\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\4\4\1\171\15\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\16\4"+
    "\1\172\3\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\10\4\1\173\11\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\13\4\1\174\6\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\14\4\1\175\5\4"+
    "\1\0\3\4\71\0\1\176\6\0\2\4\5\0\1\4"+
    "\6\0\6\4\1\177\13\4\1\0\3\4\16\0\2\4"+
    "\5\0\1\4\6\0\13\4\1\200\6\4\1\0\3\4"+
    "\16\0\2\4\5\0\1\4\6\0\1\4\1\201\20\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\12\4"+
    "\1\202\7\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\6\4\1\203\13\4\1\0\3\4\71\0\1\204"+
    "\6\0\2\4\5\0\1\4\6\0\1\4\1\205\20\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\4\4"+
    "\1\206\15\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\1\4\1\207\20\4\1\0\3\4\71\0\1\210"+
    "\6\0\2\4\5\0\1\4\6\0\4\4\1\211\15\4"+
    "\1\0\3\4\16\0\2\4\5\0\1\4\6\0\1\4"+
    "\1\212\20\4\1\0\3\4\16\0\2\4\5\0\1\4"+
    "\6\0\4\4\1\213\15\4\1\0\3\4\71\0\1\214"+
    "\6\0\2\4\1\215\2\216\2\0\1\4\6\0\22\4"+
    "\1\0\3\4\7\0\1\216\61\0\1\217\11\0\1\216"+
    "\21\0\1\220\61\0\1\220\107\0\1\221\34\0\1\222"+
    "\106\0\1\223\35\0\1\224\105\0\1\225\36\0\1\226"+
    "\104\0\1\227\61\0\1\230\61\0\1\231\61\0\1\232"+
    "\61\0\1\233\61\0\1\234\61\0\1\235\61\0\1\236"+
    "\61\0\1\237\61\0\1\240\61\0\1\241\61\0\1\242"+
    "\61\0\1\243\62\0\1\244\60\0\1\245\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6150];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\3\11\17\1\1\11\1\1\7\11"+
    "\1\1\5\11\2\1\1\11\1\1\2\0\4\11\21\1"+
    "\2\0\20\1\1\0\21\1\1\0\14\1\1\0\10\1"+
    "\1\0\5\1\1\0\3\1\1\0\3\1\12\0\1\11"+
    "\16\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public StringBuilder str;
private Symbol symbol (int type) {
        return new Symbol (type, yyline, yycolumn);
}

private Symbol symbol (int type, Object value) {
        return new Symbol (type, yyline, yycolumn, value);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  CompLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  CompLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 40: 
          { return symbol(CompSymbol.LIST);
          }
        case 49: break;
        case 13: 
          { return symbol(CompSymbol.RPAR);
          }
        case 50: break;
        case 34: 
          { return symbol(CompSymbol.TP);
          }
        case 51: break;
        case 41: 
          { return symbol(CompSymbol.STR);
          }
        case 52: break;
        case 26: 
          { return symbol(CompSymbol.DIFF);
          }
        case 53: break;
        case 31: 
          { return symbol(CompSymbol.EXIT);
          }
        case 54: break;
        case 42: 
          { return symbol(CompSymbol.INT);
          }
        case 55: break;
        case 22: 
          { return symbol(CompSymbol.COLON);
          }
        case 56: break;
        case 27: 
          { return symbol(CompSymbol.LEQL);
          }
        case 57: break;
        case 14: 
          { return symbol(CompSymbol.PLUS);
          }
        case 58: break;
        case 24: 
          { yybegin(YYINITIAL);
                 str.append('"');
                 return symbol(CompSymbol.STRING, str.toString());
          }
        case 59: break;
        case 8: 
          { return symbol(CompSymbol.NOT);
          }
        case 60: break;
        case 20: 
          { return symbol(CompSymbol.AND);
          }
        case 61: break;
        case 38: 
          { return symbol(CompSymbol.WHILE);
          }
        case 62: break;
        case 6: 
          { str= new StringBuilder();
                         str.append('"');
                         yybegin(STRING);
          }
        case 63: break;
        case 33: 
          { return symbol(CompSymbol.TRUE);
          }
        case 64: break;
        case 4: 
          { return symbol(CompSymbol.DIV);
          }
        case 65: break;
        case 30: 
          { return symbol(CompSymbol.ELSE);
          }
        case 66: break;
        case 47: 
          { return symbol(CompSymbol.MAIN);
          }
        case 67: break;
        case 2: 
          { return symbol(CompSymbol.ID, new String(yytext()));
          }
        case 68: break;
        case 15: 
          { return symbol(CompSymbol.MOD);
          }
        case 69: break;
        case 37: 
          { return symbol(CompSymbol.FLOAT);
          }
        case 70: break;
        case 5: 
          { return symbol(CompSymbol.MULT);
          }
        case 71: break;
        case 3: 
          { return symbol(CompSymbol.NB, new Integer(yytext()));
          }
        case 72: break;
        case 45: 
          { return symbol(CompSymbol.CHAR);
          }
        case 73: break;
        case 43: 
          { return symbol(CompSymbol.BOOL);
          }
        case 74: break;
        case 48: 
          { return symbol(CompSymbol.NEWBLOCK);
          }
        case 75: break;
        case 18: 
          { return symbol(CompSymbol.SEMIC);
          }
        case 76: break;
        case 17: 
          { return symbol(CompSymbol.COMMA);
          }
        case 77: break;
        case 25: 
          { return symbol(CompSymbol.EQUALS);
          }
        case 78: break;
        case 28: 
          { return symbol(CompSymbol.GEQL);
          }
        case 79: break;
        case 11: 
          { return symbol(CompSymbol.POINTER);
          }
        case 80: break;
        case 39: 
          { return symbol(CompSymbol.RETURN);
          }
        case 81: break;
        case 36: 
          { return symbol(CompSymbol.FALSE);
          }
        case 82: break;
        case 35: 
          { return symbol(CompSymbol.CLASS);
          }
        case 83: break;
        case 29: 
          { return symbol(CompSymbol.IF);
          }
        case 84: break;
        case 16: 
          { return symbol(CompSymbol.MIN);
          }
        case 85: break;
        case 21: 
          { return symbol(CompSymbol.OR);
          }
        case 86: break;
        case 10: 
          { return symbol(CompSymbol.SUP);
          }
        case 87: break;
        case 7: 
          { return symbol(CompSymbol.EQ);
          }
        case 88: break;
        case 9: 
          { return symbol(CompSymbol.INF);
          }
        case 89: break;
        case 32: 
          { return symbol(CompSymbol.NULL);
          }
        case 90: break;
        case 46: 
          { return symbol(CompSymbol.STRUCT);
          }
        case 91: break;
        case 23: 
          { str.append(yytext());
          }
        case 92: break;
        case 12: 
          { return symbol(CompSymbol.LPAR);
          }
        case 93: break;
        case 44: 
          { return symbol(CompSymbol.PROC);
          }
        case 94: break;
        case 19: 
          { return symbol(CompSymbol.ENDBLOCK);
          }
        case 95: break;
        case 1: 
          { 
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(CompSymbol.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
