
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 23 11:52:52 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompSymbol {
  /* terminals */
  public static final int ENDBLOCK = 26;
  public static final int MOD = 21;
  public static final int AND = 30;
  public static final int CLASS = 11;
  public static final int PLUS = 33;
  public static final int STRUCT = 31;
  public static final int SUP = 28;
  public static final int NB = 17;
  public static final int INT = 4;
  public static final int LIST = 9;
  public static final int CHAR = 5;
  public static final int NOT = 29;
  public static final int TRUE = 13;
  public static final int NBFLOAT = 18;
  public static final int ID = 16;
  public static final int INF = 27;
  public static final int SEMIC = 24;
  public static final int TYPE = 12;
  public static final int FLOAT = 6;
  public static final int MULT = 20;
  public static final int EOF = 0;
  public static final int MAIN = 3;
  public static final int DIV = 23;
  public static final int FALSE = 14;
  public static final int error = 1;
  public static final int POINTER = 10;
  public static final int PROC = 2;
  public static final int STR = 8;
  public static final int MIN = 22;
  public static final int BOOL = 7;
  public static final int RPAR = 32;
  public static final int NULL = 15;
  public static final int LPAR = 19;
  public static final int NEWBLOCK = 25;
}

