
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 07 10:54:38 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class MyCSymbol {
  /* terminals */
  public static final int WHILE = 4;
  public static final int SEMIC = 7;
  public static final int MAIN = 3;
  public static final int MULT = 9;
  public static final int LPAR = 5;
  public static final int PROCEDURE = 2;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int RPAR = 6;
}

